In [1]:
import numpy as np

In [2]:
n1=np.zeros((2,3))

In [3]:
n1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
n2=np.full((3,3),8)

In [5]:
n2

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [6]:
n3=np.arange(10,20,2)
n3

array([10, 12, 14, 16, 18])

In [8]:
import random
n5=np.random.randint(1,100,5)
n5

array([93, 84, 43, 76, 75])

In [10]:
n5.shape

(5,)

# Joining of Numpy array vstack,hstack and column_stack

In [13]:
import numpy as np
p1=np.array([10,20,30])
p2=np.array([40,50,60])
# np.vstack((p1,p2))
np.hstack((p1,p2))


array([10, 20, 30, 40, 50, 60])

In [14]:
np.column_stack((p1,p2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [15]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,90])
np.intersect1d(n1,n2)

array([50, 60])

In [16]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [19]:
np.setdiff1d(n2,n1)

array([70, 90])

# sum of array

In [21]:
import numpy as np
n1=np.array([10,20,30,40])
n2=np.array([50,60,70,90])
np.sum((n1,n2))

370

In [22]:
np.sum((n1,n2),axis=0)

array([ 60,  80, 100, 130])

In [23]:
np.sum((n1,n2),axis=1)

array([100, 270])

In [24]:
n1+5

array([15, 25, 35, 45])

In [25]:
n1-3

array([ 7, 17, 27, 37])

In [26]:
n2/2

array([25., 30., 35., 45.])

In [27]:
n1*2

array([20, 40, 60, 80])

In [28]:
np.mean(n1)

25.0

In [29]:
np.median(n2)

65.0

In [30]:
np.std(n2)

14.79019945774904

In [32]:
np.save('myarr',n1)

In [33]:
new_n1=np.load('myarr.npy')
new_n1

array([10, 20, 30, 40])